[package]
edition = "2024"

name = "rust-hello-world"
version = "0.0.1"
authors = ["Cody P Schafer <dev@codyps.com>"]

[dependencies]
rmp = "0.8.15"
ws-hello = { git = "https://github.com/lucasdietrich/rust-hello-world-workspace.git", rev = "a63ad47f5a7714d8a1259812bf2e44b821d3cb27"}
ws-world = { git = "https://github.com/lucasdietrich/rust-hello-world-workspace.git", rev = "a63ad47f5a7714d8a1259812bf2e44b821d3cb27"}

[profile.release]
lto = true
panic = "abort"